language: python
python:
  - "2.7"
script:
  - psql -c 'CREATE DATABASE oc;'
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install -r requirements.txt
script:
  - python manage.py test --settings=settings.test
