postgres:
  image: postgres:9.4
  volumes:
    - /data/djangopackages/postgres:/var/lib/postgresql/data
  env_file: .env
  restart: always

django:
  build: .
  user: django
  links:
    - postgres
    - redis
  command: /gunicorn.sh
  env_file: .env
  restart: always

nginx:
  build: ./compose/nginx
  links:
    - django
  ports:
    - "0.0.0.0:80:80"
  restart: always

redis:
  image: redis:3.0
  restart: always
