version: '2'

volumes:
  static: {}
  caddy: {}
  media: {}

  postgres: {}
  postgres_backup: {}
  # /data/djangopackages/postgres
  # /data-slow/djangopackages/backups


services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env

  django-failover:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env

  caddy:
    build: ./compose/caddy
    depends_on:
      - django
      - django-failover
    volumes:
      - static:/data/static
      - media:/data/media
      - caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
    env_file: .env

  redis:
    build: ./compose/redis
