version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - /data/djangopackages/postgres:/var/lib/postgresql/data
      - /data/djangopackages/backups:/backups
    env_file: .env

  django:
    build: .
    user: django
    command: /gunicorn.sh
    env_file: .env
    depends_on:
      - postgres
      - redis

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"

  redis:
    build: ./compose/redis
