dbdata:
    image: postgres:9.4
    command: "true"

db:
    extends:
        file: docker-compose.yml
        service: postgres
    volumes_from:
        - dbdata
psql:
    image: postgres:9.4
    command: psql -h db -U django django
    links:
        - db
    volumes:
        - /data/djangopackages/postgres:/var/lib/postgresql/data
