version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - /data/djangopackages/postgres:/var/lib/postgresql/data
      - /data/djangopackages/backups:/backups
    env_file: .env

  django:
    build: .
    user: django
    command: /gunicorn.sh
    env_file: .env
    depends_on:
      - postgres
      - redis

  nginx:
    build: ./compose/nginx
    expose:
      - "80"
    depends_on:
      - django

  redis:
    build: ./compose/redis
