version: '2'

volumes:
  static: {}
  caddy: {}
  media: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - /data/djangopackages/postgres:/var/lib/postgresql/data
      - /data-slow/djangopackages/backups:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env

  django-failover:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env

  caddy:
    build: ./compose/caddy
    depends_on:
      - django
      - django-failover
    volumes:
      - static:/data/static
      - media:/data/media
      - caddy:/root/.caddy
    ports:
      - "192.168.44.93:80:80"
      - "192.168.44.93:443:443"
    env_file: .env

  redis:
    build: ./compose/redis
